# Generated by Django 2.2.16 on 2022-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Текст комментария', max_length=100, verbose_name='Текст коммментария'),
        ),
    ]
