# Generated by Django 2.2.16 on 2022-11-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221117_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
