# Generated by Django 2.2.19 on 2022-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20221122_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг комментария'),
        ),
    ]
