# Generated by Django 2.2.19 on 2022-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг поста.'),
        ),
    ]
